import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
   // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    backendSideBar: [
        {
            type: 'category',
            label: 'Java',
            collapsed: true,
            items: [
                'Backend/Java/Java IO/Java IO',
                'Backend/Java/Java并发之锁/Java并发之锁',
                'Backend/Java/Java异常/Java异常',
                'Backend/Java/ThreadLocal/ThreadLocal',
                'Backend/Java/Java线程池',
                'Backend/Java/Java迭代器',
                'Backend/Java/我是一个线程',
            ],
        },
        {
            type: 'category',
            label: 'Spring',
            collapsed: true,
            items: [
                'Backend/Spring/Spring AOP实例/Spring AOP实例',
                'Backend/Spring/Spring中Bean的生命周期/Spring中Bean的生命周期',
                'Backend/Spring/Spring事务管理/Spring事务管理',
                'Backend/Spring/SSM整合/SSM整合',
                'Backend/Spring/Spring AOP理论',
                'Backend/Spring/SpringBoot参数校验',
            ],
        },
        {
            type: 'category',
            label: '数据库',
            collapsed: true,
            items: [
                'Backend/Database/MySQL事务/MySQL事务',
                'Backend/Database/SQL优化/SQL优化',
                'Backend/Database/数据库事务',
            ],
        },
    ],
    algorithmSidebar: [
        {
            type: 'category',
            label: '排序',
            collapsed: true,
            items: [
                'Wiki/Algorithm/排序/排序算法/排序算法',
                'Wiki/Algorithm/排序/冒泡排序/冒泡排序',
                'Wiki/Algorithm/排序/快速排序/快速排序',
                'Wiki/Algorithm/排序/选择排序/选择排序',
                'Wiki/Algorithm/排序/堆排序/堆排序',
                'Wiki/Algorithm/排序/插入排序/插入排序',
                'Wiki/Algorithm/排序/希尔排序/希尔排序',
                'Wiki/Algorithm/排序/归并排序/归并排序',
                'Wiki/Algorithm/排序/计数排序/计数排序',
                'Wiki/Algorithm/排序/桶排序/桶排序',
                'Wiki/Algorithm/排序/基数排序/基数排序',
            ],
        },
    ],
    designPatternSidebar: [
        'Wiki/DesignPattern/设计模式六大原则',
        'Wiki/DesignPattern/设计模式总览',
        {
            type: 'category',
            label: '创建型',
            collapsed: true,
            items: [
                "Wiki/DesignPattern/创建型/简单工厂(Factory)/简单工厂(Factory)",
                "Wiki/DesignPattern/创建型/工厂方法(FactoryMethod)/工厂方法(FactoryMethod)",
                "Wiki/DesignPattern/创建型/抽象工厂(AbstractFactory)/抽象工厂(AbstractFactory)",
                "Wiki/DesignPattern/创建型/原型(Prototype)/原型(Prototype)",
                "Wiki/DesignPattern/创建型/建造者(Builder)/建造者(Builder)",
                "Wiki/DesignPattern/创建型/单例(Singleton)",
            ],
        },
        {
            type: 'category',
            label: '结构型',
            collapsed: true,
            items: [
                "Wiki/DesignPattern/结构型/外观(Facade)/外观(Facade)",
                "Wiki/DesignPattern/结构型/适配器(Adapter)/适配器(Adapter)",
                "Wiki/DesignPattern/结构型/装饰器(Decorator)/装饰器(Decorator)",
                "Wiki/DesignPattern/结构型/享元(Flyweight)/享元(Flyweight)",
                "Wiki/DesignPattern/结构型/组合(Composite)/组合(Composite)",
                "Wiki/DesignPattern/结构型/代理(Proxy)/代理(Proxy)",
                "Wiki/DesignPattern/结构型/桥接(Bridge)/桥接(Bridge)",
            ],
        },
        {
            type: 'category',
            label: '行为型',
            collapsed: true,
            items: [
                "Wiki/DesignPattern/行为型/策略(Strategy)/策略(Strategy)",
                "Wiki/DesignPattern/行为型/访问者(Visitor)/访问者(Visitor)",
                "Wiki/DesignPattern/行为型/观察者(Observer)/观察者(Observer)",
                "Wiki/DesignPattern/行为型/责任链(Chain)/责任链(Chain)",
                "Wiki/DesignPattern/行为型/中介者(Mediator)/中介者(Mediator)",
                "Wiki/DesignPattern/行为型/迭代器(Iterator)/迭代器(Iterator)",
                "Wiki/DesignPattern/行为型/备忘录(Memento)/备忘录(Memento)",
                "Wiki/DesignPattern/行为型/命令(Command)/命令(Command)",
                "Wiki/DesignPattern/行为型/模板方法(Template)/模板方法(Template)",
                "Wiki/DesignPattern/行为型/解释器(Interpreter)",
                "Wiki/DesignPattern/行为型/状态(State)/状态(State)",
            ],
        },
    ],
    umlSidebar:[
        'Wiki/UML/类图/类图',
        'Wiki/UML/用例图/用例图',
        'Wiki/UML/时序图/时序图',
        'Wiki/UML/状态图/状态图',
    ],
    dockerSidebar: [
        "CloudNative/Docker/安装Docker/安装Docker",
        {
            type: 'category',
            label: 'Docker构建',
            collapsed: true,
            items: [
                "CloudNative/Docker/Docker构建MinIO",
                "CloudNative/Docker/Docker构建Redis/Docker构建Redis",
                "CloudNative/Docker/Docker构建Kafka/Docker构建Kafka",
                "CloudNative/Docker/Docker构建Nginx/Docker构建Nginx",
                "CloudNative/Docker/Docker构建Nacos/Docker构建Nacos",
                "CloudNative/Docker/Docker构建MongoDB/Docker构建MongoDB",
                "CloudNative/Docker/Docker构建RabbitMQ/Docker构建RabbitMQ",
                "CloudNative/Docker/Docker构建RocketMQ/Docker构建RocketMQ",
                "CloudNative/Docker/Docker构建ZooKeeper/Docker构建ZooKeeper",
                "CloudNative/Docker/Docker构建MySQL/Docker构建MySQL",
                "CloudNative/Docker/Docker构建PostgreSQL/Docker构建PostgreSQL",
                "CloudNative/Docker/Docker构建Prometheus",
                "CloudNative/Docker/Docker构建ELK/Docker构建ELK",
                "CloudNative/Docker/Docker构建OnlyOffice集群",
                "CloudNative/Docker/Docker构建Jenkins/Docker构建Jenkins",
            ],
        },
    ],
    harborSidebar: [
        "CloudNative/Harbor/安装Harbor/安装Harbor",
        "CloudNative/Harbor/Harbor安全访问/Harbor安全访问"
    ],
    orchestrationSidebar: [
        {
            type: 'category',
            label: 'K8s',
            collapsed: false,
            items: [
                "CloudNative/Orchestration/K8s/安装K8s/安装K8s",
            ],
        },
        {
            type: 'category',
            label: 'K3s',
            collapsed: false,
            items: [
                "CloudNative/Orchestration/K3s/安装K3s/安装K3s",
            ],
        },
        "CloudNative/Orchestration/Kuboard/集群管理工具Kuboard",
        "CloudNative/Orchestration/NFS存储/NFS存储"
    ],
    toolsSidebar: [
        "Tools/消息队列/RabbitMQ原理/RabbitMQ原理",
        "Tools/Redis使用",
    ],
    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
};

export default sidebars;
